services:
  - type: web
    name: cosmic-horizons-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://your-netlify-app.netlify.app
    healthCheckPath: /health
    autoDeploy: true 